name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Docker Image
        run: |
          cd frontend
          docker build -t grittynazy/frontend:latest .

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push grittynazy/frontend:latest

